server:
  port: 8080



spring:
  application:
    name: api-server
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
          filters:
            - RewritePath=/eureka/(?<segment>.*), /${segment}







eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: info
    org.springframework.cloud.gateway: TRACE
    route:
      RouteDefinitionLocator: INFO
